<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete, Edit, Plus } from '@element-plus/icons-vue'
import { apiMessage, blogApi } from '@/api'
import type { Category } from '@/types'
const items = ref<Category[]>([]); const loading = ref(false); const dialog = ref(false); const editing = ref(''); const saving = ref(false); const form = reactive({ name: '', slug: '', description: '' })
async function load() { loading.value = true; try { items.value = await blogApi.categories() } catch (error) { ElMessage.error(apiMessage(error, '分类加载失败')) } finally { loading.value = false } }
function open(item?: Category) { editing.value = item?.id || ''; Object.assign(form, item ? { name: item.name, slug: item.slug, description: item.description } : { name: '', slug: '', description: '' }); dialog.value = true }
async function save() { if (!form.name.trim()) { ElMessage.warning('请输入分类名称'); return }; saving.value = true; try { editing.value ? await blogApi.updateCategory(editing.value, form) : await blogApi.createCategory(form); ElMessage.success('分类已保存'); dialog.value = false; await load() } catch (error) { ElMessage.error(apiMessage(error, '保存失败')) } finally { saving.value = false } }
async function remove(item: Category) { try { await ElMessageBox.confirm(`确认删除分类“${item.name}”？`, '删除分类', { type: 'warning' }); await blogApi.deleteCategory(item.id); ElMessage.success('分类已删除'); await load() } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(apiMessage(error, '分类下存在文章，无法删除')) } }
onMounted(load)
</script>
<template><div class="page-stack"><section class="section-actions"><div><h2>内容分类</h2><p>保持内容结构清晰，分类被文章使用时不能删除。</p></div><el-button type="primary" :icon="Plus" @click="open()">新建分类</el-button></section><section class="data-section table-section"><el-table v-loading="loading" :data="items" empty-text="还没有分类"><el-table-column label="名称" min-width="190"><template #default="scope"><div class="post-cell"><strong>{{ scope.row.name }}</strong><small>{{ scope.row.slug }}</small></div></template></el-table-column><el-table-column prop="description" label="说明" min-width="280" show-overflow-tooltip /><el-table-column prop="postCount" label="文章数" width="100" /><el-table-column label="操作" width="130"><template #default="scope"><el-button text :icon="Edit" aria-label="编辑分类" @click="open(scope.row)" /><el-button text type="danger" :icon="Delete" aria-label="删除分类" @click="remove(scope.row)" /></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="editing ? '编辑分类' : '新建分类'" width="min(480px, 92vw)"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="form.name" maxlength="80" /></el-form-item><el-form-item label="URL 标识"><el-input v-model="form.slug" placeholder="engineering" /></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="300" show-word-limit /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
