<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Box, ChatDotRound, Delete, Edit, Promotion, Search } from '@element-plus/icons-vue'
import { apiMessage, blogApi } from '@/api'
import type { Category, Post, PostPage } from '@/types'
import { formatDate, statusLabel } from '@/utils/format'
const loading = ref(false); const page = ref<PostPage>({ items: [], total: 0, page: 1, pageSize: 20 }); const categories = ref<Category[]>([])
const filters = reactive({ q: '', status: '', categoryId: '', page: 1, pageSize: 20 })
async function load() { loading.value = true; try { page.value = await blogApi.posts(filters) } catch (error) { ElMessage.error(apiMessage(error, '文章列表加载失败')) } finally { loading.value = false } }
async function publish(post: Post) { try { await ElMessageBox.confirm(`确认发布《${post.title}》？`, '发布文章', { type: 'warning' }); await blogApi.publishPost(post.id); ElMessage.success('文章已发布'); await load() } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(apiMessage(error, '发布失败')) } }
async function archive(post: Post) { try { const current = await blogApi.post(post.id); await blogApi.updatePost(post.id, { ...current, status: 'archived' }); ElMessage.success('文章已归档'); await load() } catch (error) { ElMessage.error(apiMessage(error, '归档失败')) } }
async function remove(post: Post) { try { await ElMessageBox.confirm(`删除后无法恢复，确认删除《${post.title}》？`, '删除文章', { type: 'warning' }); await blogApi.deletePost(post.id); ElMessage.success('文章已删除'); await load() } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(apiMessage(error, '删除失败')) } }
onMounted(async () => { try { categories.value = await blogApi.categories() } catch { categories.value = [] }; await load() })
</script>
<template><div class="page-stack"><section class="filter-bar"><el-input v-model="filters.q" class="search" :prefix-icon="Search" clearable placeholder="搜索标题或正文" @keyup.enter="filters.page = 1; load()" /><el-select v-model="filters.status" clearable placeholder="全部状态" @change="filters.page = 1; load()"><el-option label="草稿" value="draft" /><el-option label="已发布" value="published" /><el-option label="已归档" value="archived" /></el-select><el-select v-model="filters.categoryId" clearable placeholder="全部分类" @change="filters.page = 1; load()"><el-option v-for="item in categories" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-button @click="filters.page = 1; load()">查询</el-button><span class="result-count">{{ page.total }} 篇文章</span></section><section class="data-section table-section"><el-table v-loading="loading" :data="page.items" empty-text="还没有文章"><el-table-column label="文章" min-width="320"><template #default="scope"><div class="post-cell"><strong>{{ scope.row.title }}</strong><small>{{ scope.row.slug }} · 更新于 {{ formatDate(scope.row.updatedAt) }}</small><div class="tag-row"><el-tag v-for="tag in scope.row.tags" :key="tag" size="small" type="info" effect="plain">{{ tag }}</el-tag></div></div></template></el-table-column><el-table-column label="分类" width="130"><template #default="scope">{{ scope.row.category?.name || '未分类' }}</template></el-table-column><el-table-column label="作者" prop="authorName" width="120" /><el-table-column label="评论" width="90"><template #default="scope"><el-button link :icon="ChatDotRound" @click="$router.push({ path: '/comments', query: { postId: scope.row.id } })">{{ scope.row.commentCount }}</el-button></template></el-table-column><el-table-column label="状态" width="105"><template #default="scope"><el-tag :type="scope.row.status === 'published' ? 'success' : scope.row.status === 'archived' ? 'info' : 'warning'" effect="plain">{{ statusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="scope"><el-tooltip content="编辑"><el-button text :icon="Edit" aria-label="编辑" @click="$router.push(`/posts/${scope.row.id}/edit`)" /></el-tooltip><el-tooltip v-if="scope.row.status !== 'published'" content="发布"><el-button text type="success" :icon="Promotion" aria-label="发布" @click="publish(scope.row)" /></el-tooltip><el-tooltip v-if="scope.row.status !== 'archived'" content="归档"><el-button text :icon="Box" aria-label="归档" @click="archive(scope.row)" /></el-tooltip><el-tooltip content="删除"><el-button text type="danger" :icon="Delete" aria-label="删除" @click="remove(scope.row)" /></el-tooltip></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.pageSize" layout="total, prev, pager, next" :total="page.total" @current-change="load" /></div></section></div></template>
